% Script to make structure of ROI details

% Define root folder
rootfolder = pwd;

% Folder to save structure
folder = fullfile(rootfolder, 'Phantom Experiments', 'Imaging Data');

% Initialise structure
ROIDetails = struct();

ROINames = {
    "ROI1",...
    "ROI2",...
    "ROI3",...
    "ROI4",...
    "ROI5",...
    "ROI6",...
    "ROI7",...
    "ROI8",...
    };


Concentrations = {
    "50% PVP",...
    "40% PVP",...
    "30% PVP",...
    "20% PVP",...
    "10% PVP",...
    "5% PVP",...
    "2.5% PVP",...
    "1mM NiCl_2",...
    };


T2s = { % ms
    126.8,...
    235.3,...
    377.1,...
    539.1,...
    693.6,...
    771.9,...
    807.3,...
    825.1,...
};


Ds = { % mm2/s
  0.120e-3,... 
  0.227e-3,... 
  0.382e-3,... 
  0.581e-3,... 
  0.833e-3,... 
  0.977e-3,... 
  1.032e-3,... 
  1.101e-3,... 
};

% Append to structure
ROIDetails.ROIName = ROINames;
ROIDetails.Concentration = Concentrations;
ROIDetails.T2 = T2s;
ROIDetails.D = Ds;


% Save structure as mat file
save(fullfile(folder,'ROIDetails.mat'), 'ROIDetails')

